### ISSUE TITLE
yolov8部署x5的代码啥时候开源啊？

### ISSUE THREAD

**Issue by APeiZou** [D-Robotics/nodehub_yolov8_object_detection#2]
@WuChao-2024    yolov8部署x5的代码啥时候开源啊？

**Comment by WuChao-2024** [comment]
你好，已经开源：
算法方案：RDK Mode Zoo：https://github.com/D-robotics/rdk_model_zoo
TROS的实时视频流推理：代码仓库： (https://github.com/D-Robotics/hobot_dnn)
